### ISSUE TITLE
Unresolved dependency while loading with Metacello

### ISSUE THREAD

**Issue by capsulecorplab** [pharo-contributions/Soup#4]
Encountered an unresolved dependency error with `GLMHighlighterTextStyleDecorator` while loading Soup with Metacello
![Screenshot from 2022-03-27 20-52-23](https://user-images.githubusercontent.com/14095576/160318642-95dcf28c-7f0f-436e-af1c-1df85823ce19.png)

**Comment by Ducasse** [comment]
Indeed. I imagine that this is Pharo 90 or 10.

**Comment by capsulecorplab** [comment]
This was on Pharo 9.0

**Comment by Ducasse** [comment]
Thanks I'm super busy. If you have a solution please send a PR. I think that this is basically the extension of GT that are failing.

**Comment by seandenigris** [comment]
Please try again with latest. Seems to load cleanly. Reopen if you find otherwise

**Comment by capsulecorplab** [comment]
still encountering same issue :confused: 
![Screenshot from 2022-09-06 21-35-09](https://user-images.githubusercontent.com/14095576/188783148-a2271bb3-9d17-474c-9e50-9b9531c790b6.png)

**Comment by Ducasse** [comment]
Hi can you check this one 

```
https://github.com/pharo-contributions/Soup

```

**Comment by Ducasse** [comment]
I will archive mine.
