### ISSUE TITLE
Proper History Preserving Authorship

### ISSUE THREAD

**Issue by seandenigris** [pharo-contributions/Soup#5]
I had ported this library in 2016 with a full history. I just redid it preserving ownership and cherrypicked all relevant commits from this repo on top of that work.

Please consider replacing the master branch of this repository with https://github.com/seandenigris/Soup/tree/history_proper. It can't be merged because it has an entirely different commit history, but you can see the changes here: https://github.com/pharo-contributions/Soup/compare/master...seandenigris:Soup:history_proper?expand=1

I will then delete my original repo and keep a fork off of this one.

**Comment by seandenigris** [comment]
cc/ @Ducasse @juliendelplanque 

I'd like to sync up before the repos diverge any more...

**Comment by Ducasse** [comment]
Hi sean 
I'm not capable to do this so I will not do it. 
We can throw away the contribution and reclone yours. 
And we can also do nothing because I'm getting tired.

S

**Comment by seandenigris** [comment]
I think I have the necessary permissions to do it myself, but I didn't want to do anything before discussing. If you are okay with it, I will stash the current master in another branch "just in case" and do as I suggested. Just let me know...

**Comment by seandenigris** [comment]
Done in cefdc02. Former master branch stashed in [old_master_wo_history](https://github.com/pharo-contributions/Soup/tree/old_master_wo_history) branch
