### ISSUE TITLE
Soup is not loading on P10

### ISSUE THREAD

**Issue by capsulecorplab** [pharo-contributions/Soup#6]
![Screenshot from 2022-10-02 11-12-20](https://user-images.githubusercontent.com/14095576/193467106-c6ec7703-9c7d-439f-91c9-447ca4e3f1d3.png)

**Comment by capsulecorplab** [comment]
Seems to primarily be an issue in Pharo 10, as it loads fine in Pharo 9
![Screenshot from 2022-10-02 11-19-25](https://user-images.githubusercontent.com/14095576/193467326-fa90b0e8-efe9-444d-bbed-c3c7f155b01f.png)

**Comment by estebanlm** [comment]
fixed (and CI proves it ;) )

**Comment by Ducasse** [comment]
Tx
