### ISSUE TITLE
TextConveter is removed from Pharo 10.  

### ISSUE THREAD

**Issue by pdebruic** [pharo-contributions/Soup#9]
https://github.com/pharo-contributions/Soup/blob/b47bd502631766d58aa768593ddacbfdbf374df5/src/Soup-Core.CustomTagClasses.package/SoupDecoder.class/instance/decodeFrom..st#L4

Seems like it should be replaced somehow with ZnCharacterEncoder.  I'm not sure.

**Comment by Ducasse** [comment]
Thanks! I do not know. 
If you find a solution, feel free to send a PR for P10.

**Comment by estebanlm** [comment]
this is fixed

**Comment by pdebruic** [comment]
@estebanlm TextConverter is still referenced here: 

https://github.com/pharo-contributions/Soup/blob/9d2e27e0015021dfae296533ff048443accc63df/src/Soup-Core.CustomTagClasses.package/SoupDecoder.class/instance/decodeFrom..st#L4

**Comment by pdebruic** [comment]
@estebanlm This issue was closed prematurely.  Please re-open it.  Thanks
